sudo: false
language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

script:
- mkdir -p build
- cd build
- cmake ..
- make
- ./tests/tests
